-- The catalog as shipped content, not a code-bundled fallback.
--
-- The app carried three copies of it: 25 recipes in the client bundle, 2 in a
-- server constant, and 2 in the database. The database is what real users are
-- served, so they saw 2 recipes while the other 23 sat unused in the JS bundle,
-- and the seeded rows had Cyrillic difficulty values that the "Easy/Medium/Hard"
-- filter could never match. This makes the database the single source of truth;
-- the bundled copies are deleted in the same change.

-- ── Store catalog: the eight products the seed file never delivered ───────────
INSERT INTO public.store_products
  (id, name, name_en, emoji, category, unit, price_per_unit, image_url, in_stock, sort_order)
VALUES
  ('00000000-0000-4000-8000-000000000009', 'Төмс',         'Potato',  '🥔', '🥦 Ногоо',      'кг', 2000,  'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&q=80', true, 90),
  ('00000000-0000-4000-8000-000000000010', 'Тахианы мах',  'Chicken', '🍗', '🥩 Мах',        'кг', 15000, 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=600&q=80', true, 100),
  ('00000000-0000-4000-8000-000000000011', 'Улаан лооль',  'Tomato',  '🍅', '🥦 Ногоо',      'кг', 4500,  'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&q=80', true, 110),
  ('00000000-0000-4000-8000-000000000012', 'Талх',         'Bread',   '🍞', '🍞 Гурилан бүтээгдэхүүн', 'ш', 2800, 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80', true, 120),
  ('00000000-0000-4000-8000-000000000013', 'Байцаа',       'Cabbage', '🥬', '🥦 Ногоо',      'ш',  3000,  'https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?w=600&q=80', true, 130),
  ('00000000-0000-4000-8000-000000000014', 'Цөцгийн тос',  'Butter',  '🧈', '🥛 Сүү, өндөг', 'ш',  9500,  'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=600&q=80', true, 140),
  ('00000000-0000-4000-8000-000000000015', 'Будаа',        'Rice',    '🍚', '🧂 Амтлагч',    'кг', 4200,  'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&q=80', true, 150),
  ('00000000-0000-4000-8000-000000000016', 'Гахайн мах',   'Pork',    '🥓', '🥩 Мах',        'кг', 18000, 'https://images.unsplash.com/photo-1602470520998-f4a52199a3d6?w=600&q=80', true, 160)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  emoji = EXCLUDED.emoji,
  category = EXCLUDED.category,
  unit = EXCLUDED.unit,
  price_per_unit = EXCLUDED.price_per_unit,
  image_url = EXCLUDED.image_url,
  in_stock = EXCLUDED.in_stock,
  sort_order = EXCLUDED.sort_order;

-- ── Recipes ───────────────────────────────────────────────────────────────────
-- Generated from the bundled catalog: 25 recipes
INSERT INTO public.recipes
  (id, title, title_en, image, tags, time, difficulty, category, cuisine, nutrition, ingredients, steps)
VALUES
  (
    'mongolian-huushuur',
    'Шүүслэг Мөнгөн Хуушуур',
    'Juicy Silver Mongolian Huushuur',
    'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    ARRAY['Монгол хоол', 'Хуушуур', 'Үндсэн хоол'],
    '35 мин',
    'Medium',
    'Үндсэн хоол',
    'Mongolian Traditional',
    '{"calories":540,"protein":28,"carbs":48,"fat":26}'::jsonb,
    ARRAY['Үхрийн мах', 'Гурил', 'Сонгино', 'Сармис', 'Давс', 'Хар перец', 'Тос'],
    '[{"stepNumber":1,"title":"Гурил зуурах ба амраах","titleEn":"Knead & Rest Dough","description":"Гурилдаа 1 чимх давс хийж бүлээн усаар дунд хатуулагтай зуурна. Гялгар уутанд боож 20 минут амраана. Зуурсны дараа дотроо агаарын бөмбөлөггүй болсныг шалгаарай.","descriptionEn":"Add a pinch of salt to flour and knead with warm water to medium-firm. Cover in plastic wrap and rest 20 minutes.","image":"https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?auto=format&fit=crop&w=800&q=80","sisterTip":"Гурилаа хэт хатуу эсвэл хэт зөөлөн зуурвал элдэхэд урагдах аюултай. Дунд зэргийн хатуулагтай зуурсан нь хамгийн зөв!","sisterTipEn":"The dough should feel like soft clay — too stiff tears, too soft sticks.","timerMinutes":20,"heatLevel":null,"stepIngredients":["Гурил (500 гр)","Бүлээн ус (150-180 мл)","Давс (1 чимх)"],"toolsNeeded":["Гурилын аяга","Гялгар уут"]},{"stepNumber":2,"title":"Мах жижиглэх ба амтлах","titleEn":"Mince & Season Meat","description":"Мах, сонгино, сармисыг нарийн жижиглэнэ. Давс, хар перец нэмж сайн холино. Бүлээн ус 2-3 хоолны халбага бага багаар нэмж шингэтэл нь базан холино.","descriptionEn":"Finely chop meat, onion, garlic. Season with salt and pepper. Gradually fold in 2-3 tbsp warm water until absorbed.","image":"https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80","sisterTip":"Маханд бүлээн ус шингээж базвал шарсны дараа шүүс нь гадагшлахгүй дотроо үлдэж хуушуур нэн шүүслэг болдог!","sisterTipEn":"Massaging warm water into filling locks moisture inside — the real secret to juicy huushuur.","timerMinutes":5,"heatLevel":null,"stepIngredients":["Үхрийн мах (500 гр жижиглэсэн)","Сонгино (2 ш нарийн хэрчсэн)","Сармис (2 хумс)","Давс, Хар перец","Бүлээн ус (3 хоолны халбага)"],"toolsNeeded":["Мах жижиглэх хутга","Холих аяга"]},{"stepNumber":3,"title":"Гурилыг элдэж хэвлэх","titleEn":"Roll Dough into Circles","description":"Амарсан гурилыг 30-35 гр-аар тасалж, тойрог хэлбэрт элдэнэ. Дунд хэсэг нь бага зэрэг зузаан, захыг нь нимгэн элдэх нь чимхэлтийг бат бэх болгоно.","descriptionEn":"Divide dough into 30-35g portions. Roll into rounds — edges thinner than the center for strong crimping.","image":"https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80","sisterTip":"Захыг нимгэн элдэхгүй бол чимхэлтийн хэсэгт гурил давхардаж, шарахад болоогүй түүхий үлдэнэ.","sisterTipEn":"Thin edges are critical — thick seams create raw doughy crimps that never cook through.","timerMinutes":null,"heatLevel":null,"stepIngredients":["Амарсан Гурилан Бөмбөлөг"],"toolsNeeded":["Гурил элдэх бариул","Гурилын шороо"]},{"stepNumber":4,"title":"Мах хийж чимхэх","titleEn":"Fill & Crimp Tightly","description":"Гурилан тойргийн нэг талд 1 хоолны халбага мах тавьж нугалаад, дотор агаар гаргахгүйгээр сонгодог монгол чимхэлтээр сайн чимхэнэ.","descriptionEn":"Place 1 tablespoon of filling on one half. Fold and press out all air. Crimp tightly using traditional Mongolian pinch pattern.","image":"https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80","sisterTip":"Агаар дотор үлдвэл шарах үед хуушуур дэлбэрэх аюултай — чимхэхийн өмнө дотроос сайн дарж агаарыг гарга!","sisterTipEn":"Trapped air = huushuur burst in hot oil. Press out every bit of air before crimping.","timerMinutes":null,"heatLevel":null,"stepIngredients":["Амтлагдсан Мах (1 халбага)","Элдсэн Гурилан Тойрог"],"toolsNeeded":["Гар — монгол чимхэлтийн техник"]},{"stepNumber":5,"title":"Тосонд шарах (170-180°C)","titleEn":"Deep Fry at 170-180°C","description":"Тосоо 170-180°C хүртэл халааж хуушуураа 4-5-аар нь нэг дор хийнэ. Тал бүрийг 3-4 минут алтан шар, шаржигнасан болтол шарна. Цаасан алчуур дээр тавьж илүүдэл тосыг шингээнэ.","descriptionEn":"Heat oil to 170-180°C. Fry in batches of 4-5 for 3-4 mins per side until golden brown. Drain on paper towels.","image":"https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80","sisterTip":"Хэт олон нэг дор хийвэл тосны дулаан буурч тос сордог — 4-5-аас хэтрүүлэхгүй байгаарай.","sisterTipEn":"Overcrowding lowers oil temperature and makes huushuur greasy. Max 4-5 at a time.","timerMinutes":8,"heatLevel":"High","stepIngredients":["Чимхсэн Хуушуур","Шарах тос (эрдэнэ шишийн, 1 л)"],"toolsNeeded":["Гүн тогоо / Фритюр","Цаасан алчуур","Шүүгч сэрээ"]}]'::jsonb
  ),
  (
    'nomad-tsuivan',
    'Уламжлалт Нүүдэлчний Цуйван',
    'Traditional Nomad Tsuivan',
    'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    ARRAY['Монгол хоол', 'Цуйван', 'Нүүдэлчин'],
    '25 мин',
    'Medium',
    'Үндсэн хоол',
    'Mongolian Traditional',
    '{"calories":580,"protein":32,"carbs":58,"fat":22}'::jsonb,
    ARRAY['Үхрийн мах', 'Гурил', 'Сонгино', 'Лууван', 'Сармис', 'Давс', 'Хар перец', 'Тос'],
    '[{"stepNumber":1,"title":"Гурил зуурч, хайруулын тавагт хайрах","titleEn":"Knead, Sear & Slice Dough","description":"Гурилыг давс, бүлээн усаар чангавтар зуурч 10 минут амраана. Нимгэн (2-3мм) элдэж нэг талыг бага тосолж, хуурай халаасан тавагт хоёр талыг тус бүр 45 секунд хайраад, 5-7 мм-ийн нарийн зураас болгон хэрчинэ.","descriptionEn":"Knead firm dough, rest 10 mins. Roll thin (2-3mm), oil one side, sear 45 sec per side in a dry hot pan, then slice into 5-7mm thin noodles.","image":"https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80","sisterTip":"Гурилаа хайрч хэрчвэл жигнэх үед нэг нэгэндээ наалдахгүй салж гүйлтэй хөвсгөр болдог — энэ бол цуйвангийн гол нууц!","sisterTipEn":"Searing before slicing is the Mongolian trick that keeps noodles perfectly separate and fluffy.","timerMinutes":15,"heatLevel":null,"stepIngredients":["Гурил (400 гр)","Давстай бүлээн ус (130 мл)","Шарах тос (1 цайны халбага)"],"toolsNeeded":["Гурил элдэх бариул","Хайруулын таваг","Хутга"]},{"stepNumber":2,"title":"Мах нарийн зурааслан шарах","titleEn":"Sear Beef Strips","description":"Үхрийн махаа нарийн, урт зурааслан хэрчинэ. Тосоо 1 хоолны халбага хийж утаа гарах хүртэл халааж, махаа нэг давхаргаар хийж тогтмол хөдөлгөлгүй 2 минут шаргалдуулна.","descriptionEn":"Slice beef into thin strips. Heat 1 tbsp oil until smoking, sear strips in a single layer for 2 mins without stirring.","image":"https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80","sisterTip":"Махаа хольж хутгахгүйгээр нэг талыг нь шаргалдуулах нь Maillard реакц үүсгэж цуйвангийн амтыг гүнзгийрүүлдэг!","sisterTipEn":"Do NOT stir the meat — let it sear undisturbed for the Maillard reaction and deep rich flavor.","timerMinutes":5,"heatLevel":"High","stepIngredients":["Үхрийн/хонины мах (400 гр нарийн зурааслан хэрчсэн)","Тос (1 хоолны халбага)"],"toolsNeeded":["Таваг/Вок","Модон хутгуур"]},{"stepNumber":3,"title":"Ногоо нэмж хуурах","titleEn":"Add Vegetables & Stir-Fry","description":"Шаржигнасан маханд сонгино, сармис, луувангаа нэмж дунд гал дээр 3-4 минут хуурна. Давс, хар перецээр амтлаад, халуун ус 1/2 аяга нэмж жигнэх суурь бий болгоно.","descriptionEn":"Add onions, garlic, carrot strips. Stir-fry 3-4 mins on medium. Season with salt and pepper. Add ½ cup hot water.","image":"https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80","sisterTip":"Луувангаа мах шиг нимгэн зурааслан хэрчвэл жигнэгдэх хугацаа ижил болж хоол жигд болдог.","sisterTipEn":"Cut carrots in thin julienne strips matching the meat size for even, synchronized cooking.","timerMinutes":4,"heatLevel":"Medium","stepIngredients":["Сонгино (2 ш зурааслан)","Лууван (2 ш нарийн зурааслан)","Сармис (3 хумс)","Давс & Хар перец","Халуун ус (1/2 аяга)"],"toolsNeeded":["Модон хутгуур","Таглаа бүхий гүн таваг"]},{"stepNumber":4,"title":"Гурилаа давхарлан жигнэх","titleEn":"Layer Noodles & Steam","description":"Мах-ногооны дээр хэрчсэн гурилыг тэгш дэлгэнэ. Тагийг нягт таглаж дунд гал дээр яг 15 минут жигнэнэ. Жигнэх явцад тагийг онгойлгохгүй байхыг анхааруулж байна!","descriptionEn":"Layer noodles evenly over meat-veg base. Cover TIGHTLY and steam on medium heat for exactly 15 mins. Do NOT open lid.","image":"https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80","sisterTip":"Тагийг жигнэх явцад онгойлговол уур гараад гурил хатаж хуурай болдог — 15 минутыг тэвчин хүлээх хэрэгтэй!","sisterTipEn":"NEVER lift the lid while steaming — escaping steam ruins perfectly cooking tsuivan noodles.","timerMinutes":15,"heatLevel":"Medium","stepIngredients":["Хэрчсэн Гурилан Зураас","Мах-Ногооны Суурь"],"toolsNeeded":["Нягт таглаатай гүн таваг"]},{"stepNumber":5,"title":"2 сэрээгээр агаар оруулж сугалах","titleEn":"Toss & Fluff with Two Forks","description":"Тагийг авч 2 сэрээгээр гурилыг доороос нь өргөж, агаар оруулж, 1-2 минут хурдан сугалан хутгана. Гурил тус тусдаа салж, мах-ногоо хооронд жигд хуваарилагдсан байх хэрэгтэй.","descriptionEn":"Uncover and toss vigorously with two forks for 1-2 mins until noodles separate and puff up with meat evenly distributed.","image":"https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80","sisterTip":"2 сэрээгээр зэрэг өргөж хутгах нь ресторан чанартай цуйвангийн нууц — нэг сэрээгээр тэр амт гардаггүй шүү!","sisterTipEn":"Two forks simultaneously = restaurant-grade fluffy tsuivan. One fork just doesn''t cut it!","timerMinutes":2,"heatLevel":null,"stepIngredients":null,"toolsNeeded":["2 ширхэг сэрээ","Халуун хоолны аяга"]}]'::jsonb
  ),
  (
    'bortts-dumpling-tea',
    'Борцтой Банштай Цай',
    'Mongolian Bortts Dumpling Milk Tea',
    'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80',
    ARRAY['Монгол цай', 'Борц', 'Банштай цай'],
    '20 мин',
    'Medium',
    'Шөл ба Бүлээн хоол',
    'Mongolian Traditional',
    '{"calories":430,"protein":29,"carbs":30,"fat":22}'::jsonb,
    ARRAY['Борц', 'Гурил', 'Сүү', 'Шар тос / Сүүлний тос', 'Үхрийн мах', 'Сонгино', 'Давс', 'Хар перец'],
    '[{"stepNumber":1,"title":"Борц дэвтээх ба банш чимхэх","titleEn":"Soak Dried Beef & Fold Dumplings","description":"Борцоо бага зэрэг халуун усанд 15 минут дэвтээнэ. Махаа сонгино, давс, перецээр амтлан гуриланд чимхэж банш бэлтгэнэ.","descriptionEn":"Soak dried beef in warm water. Mix minced meat with onions and spices, fold into dumplings.","image":"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80","sisterTip":"Борцыг дэвтээснээр шөлөнд амт нь түргэн уусаж маш сайхан үнэр орно.","sisterTipEn":"Soaking dried beef releases deep umami into the milk tea.","timerMinutes":null,"heatLevel":null,"stepIngredients":null,"toolsNeeded":null},{"stepNumber":2,"title":"Цай сүүлэх ба борц хуурах","titleEn":"Brew Milk Tea & Sauté Bortts","description":"Ногоон цайгаа чанаж шүүгээд, дээр нь сүү, давс нэмж сүүлэн самрна. Шар тосонд дэвтээсэн борцоо нэмж 2-3 минут хөнгөн хуурна.","descriptionEn":"Brew green tea, add milk and salt, churn well. Sauté soaked dried beef in yellow butter.","image":"https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80","sisterTip":"Шар тосонд борцоо хуурч цайгаа сүүлбэл жинхэнэ нүүдэлчдийн тансаг цай болно.","sisterTipEn":"Sautéing dried beef in ghee adds traditional richness.","timerMinutes":null,"heatLevel":null,"stepIngredients":null,"toolsNeeded":null},{"stepNumber":3,"title":"Чанаж гүйцээх","titleEn":"Simmer Tea & Cook Dumplings","description":"Хуурсан борц дээрээ сүүлсэн цайгаа хийж буцалгана. Цай буцалмагц баншаа хийж, тагийг нь таглаад 8-10 минут буцалгахад банш хөвж гарна.","descriptionEn":"Pour milk tea into the pot with sautéed bortts, bring to boil, drop in dumplings and simmer 8-10 mins.","image":"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80","sisterTip":"Банш хөвж гармагц халуун дулаанаар нь таваглаарай.","sisterTipEn":"Serve steaming hot as soon as the dumplings float.","timerMinutes":null,"heatLevel":null,"stepIngredients":null,"toolsNeeded":null}]'::jsonb
  ),
  (
    'avocado-toast',
    'Авокадотой Бүрэн Үрийн Тост ба Шингэн Шартай Өндөг',
    'Avocado Toast & Poached Egg',
    'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80',
    ARRAY['Өглөөний цай', 'Эрүүл', 'Протеин'],
    '10 мин',
    'Easy',
    'Өглөөний цай',
    'Healthy Fusion',
    '{"calories":320,"protein":14,"carbs":28,"fat":18}'::jsonb,
    ARRAY['Бүрэн үрийн талх', 'Өндөг', 'Авокадо', 'Оливын тос', 'Давс', 'Хар перец'],
    '[{"stepNumber":1,"title":"Талх ба авокадо бэлтгэх","titleEn":"Prepare Toast & Mash Avocado","description":"Бүрэн үрийн талхаа шарж, авокадогоо сэрээгээр нухаж оливын тос, нимбэгийн шүүсээр амтална.","descriptionEn":"Toast whole grain bread and mash avocado with olive oil, lemon juice, and seasonings.","image":"https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?auto=format&fit=crop&w=800&q=80","sisterTip":"Авокадо дээрээ чили флейкс цацвал өглөөний эрч хүч нэмэгдэнэ!","sisterTipEn":"Add chili flakes for a morning boost!","timerMinutes":null,"heatLevel":null,"stepIngredients":null,"toolsNeeded":null},{"stepNumber":2,"title":"Өндөг чанах (Poached Egg)","titleEn":"Poach Eggs","description":"Бага зэрэг буцалж буй усанд цуу нэмээд өндгөө 3 минут чанаж, шарыг нь зөөлөн үлдээнэ.","descriptionEn":"Poach eggs in simmering water with vinegar for 3 minutes until yolk remains runny.","image":"https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80","sisterTip":"Усаа эргүүлж хуй үүсгээд өндгөө яг дунд нь хийвэл хэлбэр нь төгс гардаг шүү.","sisterTipEn":"Create a whirlpool in the water before dropping the egg in.","timerMinutes":null,"heatLevel":null,"stepIngredients":null,"toolsNeeded":null}]'::jsonb
  ),
  (
    'overnight-oats',
    'Овъёосны Шөнө Хоносон Пудинг (Chia Overnight Oats)',
    'Chia Overnight Oats with Berries',
    'https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&w=800&q=80',
    ARRAY['Овъёос', 'Детокс', 'Түргэн'],
    '5 мин',
    'Easy',
    'Өглөөний цай',
    'Global',
    '{"calories":280,"protein":11,"carbs":42,"fat":8}'::jsonb,
    ARRAY['Овъёос', 'Сүү', 'Чиа үр', 'Зөгийн бал', 'Жимс', 'Самрын тос'],
    '[{"stepNumber":1,"title":"Хольж бэлтгэх","titleEn":"Mix Ingredients","description":"Шилэн саванд овъёос, чиа үр, сүү, зөгийн балаа сайтар хутгаж хөргөгчид хонуулна.","descriptionEn":"Combine oats, chia seeds, milk, and honey in a jar. Chill overnight.","image":"https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&w=800&q=80","sisterTip":"Өглөө нь шинэхэн бөөрөлзгөнө, самрын тос нэмж амтлаарай!","sisterTipEn":"Top with berries and peanut butter in the morning.","timerMinutes":null,"heatLevel":null,"stepIngredients":null,"toolsNeeded":null}]'::jsonb
  ),
  (
    'green-smoothie-bowl',
    'Шпинат ба Кивитэй Ногоон Смузи Боул',
    'Green Spinach & Kiwi Smoothie Bowl',
    'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
    ARRAY['Смузи', 'Ногоон', 'Бага илчлэг'],
    '8 мин',
    'Easy',
    'Өглөөний цай',
    'Healthy',
    '{"calories":210,"protein":6,"carbs":45,"fat":3}'::jsonb,
    ARRAY['Шпинат', 'Банан', 'Киви', 'Кокосын ус', 'Гранола'],
    '[{"stepNumber":1,"title":"Блендерээр холих","titleEn":"Blend Smoothie","description":"Шпинат, хөлдөөсөн банан, киви, кокосын усыг блендерт хийж өтгөн болтол сайтар нухна.","descriptionEn":"Blend spinach, frozen banana, kiwi, and coconut water until smooth and thick.","image":"https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80","sisterTip":"Мөсний оронд хөлдөөсөн банан хэрэглэвэл илүү крем шиг зөөлөн болно.","sisterTipEn":"Use frozen banana instead of ice for a creamier texture.","timerMinutes":null,"heatLevel":null,"stepIngredients":null,"toolsNeeded":null}]'::jsonb
  ),
  (
    'greek-protein-omelet',
    'Грек Тарагтай Уургийн Омлет',
    'Greek Yogurt Protein Omelet',
    'https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=800&q=80',
    ARRAY['Омлет', 'Өндөг', 'High Protein'],
    '12 мин',
    'Easy',
    'Өглөөний цай',
    'Mediterranean',
    '{"calories":310,"protein":26,"carbs":7,"fat":19}'::jsonb,
    ARRAY['Өндөг', 'Грек тараг', 'Черри томат', 'Шпинат', 'Оливын тос'],
    '[{"stepNumber":1,"title":"Өндөг хутгах","titleEn":"Whisk & Fry","description":"Өндгөө Грек тарагтай сайтар хутгаж, бага тосонд зөөлөн галаар шараад гурвалжин нугална.","descriptionEn":"Whisk eggs with Greek yogurt for extra fluffiness and fry gently in olive oil.","image":"https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=800&q=80","sisterTip":"Грек тараг нэмснээр омлет өндөр уурагтай бөгөөд хөвсгөр зөөлөн болно.","sisterTipEn":"Greek yogurt makes the omelet ultra-fluffy and protein-dense.","timerMinutes":null,"heatLevel":null,"stepIngredients":null,"toolsNeeded":null}]'::jsonb
  ),
  (
    'salmon-nicoise-salad',
    'Сэлмон Загастай Нисуаз Салат',
    'Salmon Nicoise Salad',
    'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    ARRAY['Сэлмон', 'Салат', 'Омега3'],
    '20 мин',
    'Medium',
    'Салат ба Хөнгөн зууш',
    'French',
    '{"calories":380,"protein":32,"carbs":12,"fat":22}'::jsonb,
    ARRAY['Сэлмон загас', 'Өндөг', 'Черри томат', 'Олив', 'Ногоон салат'],
    '[{"stepNumber":1,"title":"Загас шарж таваглах","titleEn":"Sear Salmon & Assemble","description":"Сэлмон загасаа оливын тос, нимбэгээр амталж 5 минут шараад чанасан өндөг, черри томаттай таваглана.","descriptionEn":"Pan-sear salmon, slice eggs, toss with fresh greens, cherry tomatoes and Dijon vinaigrette.","image":"https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80","sisterTip":"Сэлмоноо хэт шарж хатаахгүй, голыг нь шүүслэг үлдээгээрэй!","sisterTipEn":"Keep the salmon juicy in the middle!","timerMinutes":null,"heatLevel":null,"stepIngredients":null,"toolsNeeded":null}]'::jsonb
  ),
  (
    'quinoa-greek-salad',
    'Киноа ба Грек Салат',
    'Quinoa Greek Mediterranean Salad',
    'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
    ARRAY['Киноа', 'Вегетариан', 'Грек'],
    '15 мин',
    'Easy',
    'Салат ба Хөнгөн зууш',
    'Greek',
    '{"calories":310,"protein":12,"carbs":36,"fat":14}'::jsonb,
    ARRAY['Киноа', 'Өргөст хэмх', 'Фета бяслаг', 'Олив', 'Улаан сонгино'],
    '[{"stepNumber":1,"title":"Киноа чанах ба салат хутгах","titleEn":"Cook Quinoa & Toss","description":"Чанаж хөргөсөн киноаг өргөст хэмх, фета бяслаг, оливын тос ба ореганогоор амтлан холино.","descriptionEn":"Combine cooked cool quinoa with diced cucumber, olives, feta, olive oil and oregano.","image":"https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80","sisterTip":"Фета бяслагаа гараараа буталж хийвэл амт нь жигд тардаг.","sisterTipEn":"Crumble feta by hand for even flavor distribution.","timerMinutes":null,"heatLevel":null,"stepIngredients":null,"toolsNeeded":null}]'::jsonb
  ),
  (
    'chicken-kale-caesar',
    'Тахианы Цээж Махтай Кейл Цезарь Салат',
    'Chicken Kale Caesar Salad',
    'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&w=800&q=80',
    ARRAY['Тахиа', 'Цезарь', 'Кейл'],
    '20 мин',
    'Easy',
    'Салат ба Хөнгөн зууш',
    'American',
    '{"calories":390,"protein":35,"carbs":16,"fat":20}'::jsonb,
    ARRAY['Тахианы цээж мах', 'Кейл / Ромэн салат', 'Пармезан бяслаг', 'Сухари', 'Цезарь соус'],
    '[{"stepNumber":1,"title":"Тахианы мах шарах","titleEn":"Grill Chicken & Toss","description":"Тахианы цээж махаа амталж грилл дээр шараад кейл навч, пармезан, хөнгөн соустай хамт таваглана.","descriptionEn":"Grill seasoned chicken breast, slice thinly, and toss with massaged kale and Parmesan.","image":"https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&w=800&q=80","sisterTip":"Кейл навчаа оливын тосоор 1 минут базвал зөөлөн бөгөөд амттай болно.","sisterTipEn":"Massage kale leaves with olive oil to soften them.","timerMinutes":null,"heatLevel":null,"stepIngredients":null,"toolsNeeded":null}]'::jsonb
  ),
  (
    'hummus-veggie-platter',
    'Хумустай Ногооны Таваг (Hummus Platter)',
    'Fresh Hummus & Fresh Veggie Platter',
    'https://images.unsplash.com/photo-1541529086526-db283c563270?auto=format&fit=crop&w=800&q=80',
    ARRAY['Хумус', 'Веган', 'Снэк'],
    '10 мин',
    'Easy',
    'Салат ба Хөнгөн зууш',
    'Middle Eastern',
    '{"calories":250,"protein":9,"carbs":32,"fat":10}'::jsonb,
    ARRAY['Нут шош (хумус)', 'Лууван', 'Өргөст хэмх', 'Чипс / Пита талх', 'Оливын тос'],
    '[{"stepNumber":1,"title":"Ногоо хэрчих ба таваглах","titleEn":"Slice & Serve","description":"Лууван, өргөст хэмхийг урт нарийн хэрчиж, хумус болон паприка, оливын тостой хамт дэлгэнэ.","descriptionEn":"Slice fresh carrots, cucumbers, and celery into sticks. Serve around fresh hummus.","image":"https://images.unsplash.com/photo-1541529086526-db283c563270?auto=format&fit=crop&w=800&q=80","sisterTip":"Хумус дээрээ чимх паприка цацаж, оливын тос дуслуулаарай.","sisterTipEn":"Drizzle extra virgin olive oil and paprika over the hummus.","timerMinutes":null,"heatLevel":null,"stepIngredients":null,"toolsNeeded":null}]'::jsonb
  ),
  (
    'lasagna',
    'Лазанья',
    'Classic Beef Lasagna',
    'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?auto=format&fit=crop&w=800&q=80',
    ARRAY['Лазанья', 'Үхрийн мах', 'Итали'],
    '60 мин',
    'Hard',
    'Үндсэн хоол',
    'Italian',
    '{"calories":680,"protein":38,"carbs":54,"fat":32}'::jsonb,
    ARRAY['Үхрийн мах', 'Гурил', 'Сүү', 'Бяслаг', 'Томат соус', 'Сонгино'],
    '[{"stepNumber":1,"title":"Сонгино & Сармис хуурч бэлтгэх","titleEn":"Sauté Onions & Garlic","description":"Гүн хайруулын тавгаа дунд гал дээр халааж, 2 хоолны халбага оливын тосонд нарийн жижиглэсэн сонгино, сармисаа алтан шар өнгөтэй, анхилуун үнэртэй болтол 4-5 минут хуурна.","descriptionEn":"Heat olive oil in a deep pan, sauté finely chopped onions and garlic until translucent and fragrant.","image":"https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80","sisterTip":"Сонгиноо зөөлөн гал дээр карамельжуулбал соусны амт байгалийн чихэрлэг бөгөөд тансаг болдог.","sisterTipEn":"Slowly caramelizing onions creates a naturally sweet flavor base.","timerMinutes":5,"heatLevel":"Medium","stepIngredients":["Сонгино (1 ш жижиглэсэн)","Сармис (3 хумс)","Оливын тос (2 хоолны халбага)"],"toolsNeeded":["Гүн хайруулын таваг","Модон хутгуур"]},{"stepNumber":2,"title":"Үхрийн мах & Болоньез соус бэлтгэх","titleEn":"Bolognese Meat Sauce","description":"Хуурсан сонгино дээрээ үхрийн татсан махаа нэмж, бөөгнөрөхгүйгээр задартал хуурна. Дараа нь томат паста, орегано, давс, хар перец нэмж 12 минут зөөлөн гал дээр самран буцалгана.","descriptionEn":"Add minced beef, cook until browned. Stir in tomato sauce, oregano, salt, and pepper. Simmer for 12 mins.","image":"https://images.unsplash.com/photo-1546549032-9571cd6b27df?auto=format&fit=crop&w=800&q=80","sisterTip":"Соус буцалж байхад 1 чимх саахар нэмбэл томатын хүчиллэг чанарыг зөөллөж амтыг нь тэнцвэржүүлнэ.","sisterTipEn":"Adding a pinch of sugar balances the acidity of the tomatoes.","timerMinutes":12,"heatLevel":"Low","stepIngredients":["Үхрийн татсан мах (500 гр)","Томат паста (300 мл)","Орегано амтлагч (1 цайны халбага)","Давс & Хар перец"],"toolsNeeded":["Модон хутгуур","Таглаа"]},{"stepNumber":3,"title":"Бешамель (Цагаан соус) чанах","titleEn":"Prepare Béchamel Sauce","description":"Жижиг саванд шар тосоо хайлуулж гурилаа нэмэн 1 минут хуурна. Бүлээн сүүгээ бага багаар гоожуулан хутгууртаар тасралтгүй хутгаж, өтгөртөл 6-8 минут зөөлөн гал дээр чанана.","descriptionEn":"Melt butter, add flour, cook 1 min. Gradually whisk in warm milk and cook until thick and creamy.","image":"https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80","sisterTip":"Сүүгээ бүлээнээр нь бага багаар нэмж хутгуурыг зогсолтгүй хөдөлгөвөл соус бөөгнөрөхгүй торгомсог болно.","sisterTipEn":"Whisk continuously while pouring warm milk to achieve a silky smooth texture.","timerMinutes":8,"heatLevel":"Low","stepIngredients":["Шар тос / Маргарин (50 гр)","Гурил (2 хоолны халбага)","Бүлээн сүү (500 мл)","Мускат самар (1 чимх)"],"toolsNeeded":["Шөлний жижиг сав","Гар хутгуур (Whisk)"]},{"stepNumber":4,"title":"Лазанья гоймон чанах ба зөөлрүүлэх","titleEn":"Boil Lasagna Sheets","description":"Том тогоонд усаа сайн буцалгаж 1 чимх давс нэмнэ. Гоймоны хуудсуудыг 5-6 минут чанаж зөөлрүүлээд шүүж, наалдуулахгүйн тулд цэвэр алчуур дээр дэлгэн тавина.","descriptionEn":"Boil lasagna sheets in salted water for 5-6 mins. Drain and lay flat on a clean cloth to prevent sticking.","image":"https://images.unsplash.com/photo-1621996346565-e3d5d6281318?auto=format&fit=crop&w=800&q=80","sisterTip":"Чанах усандаа хэдэн дусал оливын тос дусгавал гоймон чанах үед бие биедээ наалдахгүй.","sisterTipEn":"A drop of olive oil in boiling water keeps sheets from sticking together.","timerMinutes":6,"heatLevel":"High","stepIngredients":["Лазанья гоймон (12 хуудас)","Давстай буцалсан ус"],"toolsNeeded":["Том тогоо","Шүүгч сэрээ"]},{"stepNumber":5,"title":"Хэвэнд давхарлан угсрах (Layering)","titleEn":"Assemble Lasagna Layers","description":"Дөрвөлжин шилэн хэвний ёроолд бешамель соусыг нимгэн түрхэнэ. Гоймон -> Болоньез махны соус -> Бешамель цагаан соус -> Моцарелла бяслаг гэх дарааллаар 3-4 үе давхарлана.","descriptionEn":"Spread béchamel on baking dish bottom. Layer sheets, meat sauce, béchamel, and mozzarella cheese.","image":"https://images.unsplash.com/photo-1574894709920-11b28e7367e3?auto=format&fit=crop&w=800&q=80","sisterTip":"Хамгийн дээд үе дээр бешамель соус болон Моцарелла бяслагаа зузаан бүрж цацаарай.","sisterTipEn":"Top with a rich layer of béchamel and shredded mozzarella for maximum cheesiness.","timerMinutes":5,"heatLevel":null,"stepIngredients":["Моцарелла бяслаг (250 гр хэрчсэн)","Үрсэн Пармезан бяслаг (50 гр)"],"toolsNeeded":["Шарах шүүгээний дөрвөлжин шилэн хэв"]},{"stepNumber":6,"title":"Шарах шүүгээнд жигнэж шаргалдуулах","titleEn":"Bake to Golden Perfection","description":"190°C хүртэл халаасан шарах шүүгээнд фольга цаасаар таглаж 20 минут, дараа нь цаасыг авч бяслагийг алтан бор шаржигнасан болтол 8 минут шарна. Гаргаад 10 минут амраасны дараа зүснэ.","descriptionEn":"Cover with foil and bake at 190°C for 20 mins. Uncover and bake 8 mins until cheese is golden brown. Rest 10 mins.","image":"https://images.unsplash.com/photo-1546549032-9571cd6b27df?auto=format&fit=crop&w=800&q=80","sisterTip":"Шарах шүүгээнээс гарсан дор нь шууд зүсэлгүй 10 минут амраавал давхаргууд нь нурахгүй, тэгш сайхан зүсэгдэнэ.","sisterTipEn":"Letting the lasagna rest for 10 mins sets the layers perfectly for neat slicing.","timerMinutes":28,"heatLevel":"Medium","stepIngredients":["Амраасан Лазанья"],"toolsNeeded":["Шарах шүүгээ (190°C)","Фольга цаас","Тогоочийн хутга"]}]'::jsonb
  ),
  (
    'carbonara',
    'Карбонара Паста',
    'Spaghetti Carbonara',
    'https://images.unsplash.com/photo-1612874742237-6526221588e3?auto=format&fit=crop&w=800&q=80',
    ARRAY['Гоймон', 'Өндөг', 'Итали'],
    '20 мин',
    'Medium',
    'Үндсэн хоол',
    'Italian',
    '{"calories":520,"protein":24,"carbs":62,"fat":20}'::jsonb,
    ARRAY['Гурил', 'Өндөг', 'Бяслаг', 'Сармис'],
    '[{"stepNumber":1,"title":"Спагетти гоймон чанах","titleEn":"Boil Spaghetti Al Dente","description":"Том тогоонд ус буцалгаж 1 хоолны халбага давс нэмнэ. Спагетти гоймонгоо хийж сав дахь зааврын дагуу (ихэвчлэн 9-10 мин) al dente буюу шүдэнд бага зэрэг зууртай болтол чанана. Чанасан уснаас 1 аяга нөөцлөж авна.","descriptionEn":"Boil pasta in heavily salted water for 9-10 mins until al dente. Reserve 1 cup of pasta water before draining.","image":"https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80","sisterTip":"Гоймон чанасан давстай усыг заавал нөөцөлж аваарай — энэ бол карбонарын соусыг хамгийн торгомсог, кремлэг болгодог нууц зэвсэг!","sisterTipEn":"Pasta water is liquid gold for carbonara — its starch makes the sauce unbelievably silky and emulsified.","timerMinutes":10,"heatLevel":"High","stepIngredients":["Спагетти гоймон (400 гр)","Давстай буцалсан ус (4 л)","Нөөцлөх ус (1 аяга)"],"toolsNeeded":["Том тогоо","Гоймоны ус нөөцлөх аяга","Шүүгч сэрээ"]},{"stepNumber":2,"title":"Гуанчале / Бекон шарах","titleEn":"Render Guanciale / Bacon","description":"Хайруулын тавагт тос хийлгүй гуанчале буюу бекон мах нарийн зурааслан хэрчсэнийг тавьж зөөлөн гал дээр 4-5 минут тосыг нь гаргаж, шаржигнатал хуурна.","descriptionEn":"Without any added oil, render guanciale/bacon strips in pan on medium-low for 4-5 mins until crispy fat renders out.","image":"https://images.unsplash.com/photo-1621996346565-e3d5d6288307?auto=format&fit=crop&w=800&q=80","sisterTip":"Тос нэмэхгүйгээр өөрийн тосыг нь гаргах нь бекон/гуанчале-г маш шаржигнасан, дотор нь хайлмаг болгодог шүү.","sisterTipEn":"No added oil — render the fat from the pork itself for the most authentic, rich carbonara flavor.","timerMinutes":5,"heatLevel":"Low","stepIngredients":["Гуанчале / Бекон (150 гр нарийн зурааслан)"],"toolsNeeded":["Хайруулын таваг","Металл хутгуур"]},{"stepNumber":3,"title":"Өндөг & Бяслагны холимог бэлтгэх","titleEn":"Whisk Egg & Cheese Mixture","description":"Том аяганд өндгийн 3 шар, Пармезан (эсвэл Пекорино) бяслаг сайн үрж хийж, хар перец сайтар нэмнэ. Сайтар хутгаж жигд холино. Энэ холимог галд огт хүрэхгүй — зөвхөн гоймоны дулаанаар зуурагдана.","descriptionEn":"In a bowl, whisk 3 egg yolks with finely grated parmesan and generous black pepper. This MUST never touch direct heat.","image":"https://images.unsplash.com/photo-1612874742237-6526221588e3?auto=format&fit=crop&w=800&q=80","sisterTip":"Өндгийг шууд галд тавивал тэр дороо бүлэгнэж хатна — Scrambled Eggs болчихно! Заавал галаас нь холдуулаарай.","sisterTipEn":"NEVER put eggs near heat — they WILL scramble instantly. The only heat they need is from the warm pasta itself.","timerMinutes":null,"heatLevel":null,"stepIngredients":["Өндгийн шар (3 ширхэг)","Пармезан бяслаг (80 гр нарийн үрсэн)","Хар перец (1 цайны халбага шинэ бутарсан)"],"toolsNeeded":["Холих аяга","Хутгуур","Бяслаг үрэгч"]},{"stepNumber":4,"title":"Бүх зүйлийг нэгтгэх — Галаас гаргасны дараа!","titleEn":"Combine Off Heat — This Step is Sacred","description":"Гоймоныг шүүж беконтой хайруулын тавагт хийнэ. ГАЛААС ГАРГА. Өндгийн холимогоо хийж хурдан хутгана. Нөөцөлсөн гоймоны уснаас 2-3 хоолны халбага нэмж, торгомсог кремлэг болтол хурдан хутгана.","descriptionEn":"Drain pasta into bacon pan. REMOVE FROM HEAT. Add egg mixture immediately. Toss rapidly. Add pasta water 1 tbsp at a time until glossy and creamy.","image":"https://images.unsplash.com/photo-1612874742237-6526221588e3?auto=format&fit=crop&w=800&q=80","sisterTip":"Гоймоны ус нэмэх нь өндгийг тогтвортой эмульс болгодог — хэт их нэмэлгүй 1-2 хоолны халбагаар тохируулаарай.","sisterTipEn":"Add pasta water one spoon at a time — it emulsifies the eggs into glossy silk. This is the soul of real carbonara.","timerMinutes":3,"heatLevel":null,"stepIngredients":["Чанасан Спагетти","Шаржигнасан Бекон","Өндөг-Бяслагны Холимог","Нөөцөлсөн Гоймоны Ус (2-4 хоолны халбага)"],"toolsNeeded":["2 халбага (хурдан хутгахад)","Дулаан хоолны аяга"]}]'::jsonb
  ),
  (
    'lemon-herb-grilled-salmon',
    'Нимбэг, Анхилуун Ургамлаар Амталсан Шарсан Сэлмон',
    'Lemon Herb Grilled Salmon with Asparagus',
    'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=800&q=80',
    ARRAY['Сэлмон', 'Зөөлөн', 'Keto'],
    '20 мин',
    'Easy',
    'Үндсэн хоол',
    'Gourmet',
    '{"calories":420,"protein":36,"carbs":6,"fat":28}'::jsonb,
    ARRAY['Сэлмон загас', 'Нимбэг', 'Сармис', 'Розмарин', 'Оливын тос', 'Аспарагус'],
    '[{"stepNumber":1,"title":"Сэлмон шарах","titleEn":"Sear & Roast Salmon","description":"Сэлмон загасаа нимбэгийн шүүс, сармис, розмаринаар амтлаад грилл дээр 12 минут шарна.","descriptionEn":"Season salmon fillet with fresh lemon juice, minced garlic, and rosemary. Pan-sear then bake.","image":"https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=800&q=80","sisterTip":"Аспарагусыг хамт шарвал төгс зохицдог.","sisterTipEn":"Roast asparagus alongside for the perfect side dish.","timerMinutes":null,"heatLevel":null,"stepIngredients":null,"toolsNeeded":null}]'::jsonb
  ),
  (
    'broccoli-chicken-grill',
    'Брокколи ба Сармистай Тахианы Цээж Махны Грилл',
    'Garlic Broccoli Chicken Stir-Fry',
    'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=800&q=80',
    ARRAY['Тахиа', 'Брокколи', 'Fit'],
    '25 мин',
    'Medium',
    'Үндсэн хоол',
    'Asian',
    '{"calories":380,"protein":44,"carbs":14,"fat":12}'::jsonb,
    ARRAY['Тахианы цээж мах', 'Брокколи', 'Сармис', 'Сой соус', 'Гүнжид'],
    '[{"stepNumber":1,"title":"Тахиа ба брокколи хуурах","titleEn":"Stir-Fry Chicken & Broccoli","description":"Тахианы махаа дөрвөлжин хэрчиж сой соусаар амтлаад брокколитой өндөр гал дээр хуурна.","descriptionEn":"Diced chicken breasts sautéed with broccoli florets, garlic, and light soy sauce.","image":"https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=800&q=80","sisterTip":"Гүнжидийн тос сүүлд нь дусгавал Ази ресторанд байгаа юм шиг анхилуун болно.","sisterTipEn":"Drizzle sesame oil at the end for an authentic aroma.","timerMinutes":null,"heatLevel":null,"stepIngredients":null,"toolsNeeded":null}]'::jsonb
  ),
  (
    'low-carb-beef-stew',
    'Нүүрс Ус Багатай Үхрийн Мах, Ногооны Гуляш',
    'Low-Carb Beef Veggie Stew',
    'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    ARRAY['Үхрийн мах', 'Гуляш', 'Шөлтэй'],
    '35 мин',
    'Medium',
    'Үндсэн хоол',
    'Traditional',
    '{"calories":410,"protein":42,"carbs":16,"fat":20}'::jsonb,
    ARRAY['Үхрийн мах', 'Цэцэгт байцаа', 'Лууван', 'Томат паста', 'Сонгино'],
    '[{"stepNumber":1,"title":"Үхрийн мах ба ногоо жигнэх","titleEn":"Slow Simmer Beef & Veggies","description":"Үхрийн махаа дөрвөлжин хэрчиж, сонгино, томат пастатай хамт жигнээд ногоогоо зөөлрөх хүртэл буцалгана.","descriptionEn":"Simmer tender beef cubes with cauliflower, carrots, and tomato broth.","image":"https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80","sisterTip":"Төмсний оронд цэцэгт байцаа хэрэглэснээр нүүрс ус маш багатай болно.","sisterTipEn":"Swap potatoes for cauliflower for a low-carb alternative.","timerMinutes":null,"heatLevel":null,"stepIngredients":null,"toolsNeeded":null}]'::jsonb
  ),
  (
    'pad-thai',
    'Пад Тай',
    'Authentic Shrimp Pad Thai',
    'https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=800&q=80',
    ARRAY['Пад Тай', 'Сам хорхой', 'Тайланд'],
    '25 мин',
    'Medium',
    'Үндсэн хоол',
    'Thai',
    '{"calories":450,"protein":26,"carbs":58,"fat":14}'::jsonb,
    ARRAY['Гоймон', 'Сам хорхой', 'Өндөг', 'Самрын үйрмэг', 'Нимбэг'],
    '[{"stepNumber":1,"title":"Будааны гоймон бэлтгэх","titleEn":"Soak Noodles & Wok Fry","description":"Будааны гоймонгоо дэвтээж, сам хорхой ба өндөгтэй хамт вок тогоонд хуурна.","descriptionEn":"Soak rice noodles, then stir-fry with shrimp, scrambled egg, tamarind sauce.","image":"https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=800&q=80","sisterTip":"Нимбэгийн шүүс, газрын самар нэмж өгвөл Тайландын жинхэнэ амт орно.","sisterTipEn":"Finish with fresh lime juice and crushed peanuts.","timerMinutes":null,"heatLevel":null,"stepIngredients":null,"toolsNeeded":null}]'::jsonb
  ),
  (
    'pumpkin-soup',
    'Шарсан Хулууны Зутан Шөл',
    'Creamy Roasted Pumpkin Soup',
    'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?auto=format&fit=crop&w=800&q=80',
    ARRAY['Хулуу', 'Шөл', 'Зутан'],
    '30 мин',
    'Easy',
    'Шөл ба Бүлээн хоол',
    'European',
    '{"calories":210,"protein":5,"carbs":32,"fat":8}'::jsonb,
    ARRAY['Амтат хулуу', 'Сүү', 'Сонгино', 'Сармис', 'Тос'],
    '[{"stepNumber":1,"title":"Хулуу шарж нухах","titleEn":"Roast & Blend","description":"Хулуугаа шарах шүүгээнд шараад сонгино, сармистай хуурна. Дараа нь блендерээр жигд нухаж зутан шөл болгоно.","descriptionEn":"Roast pumpkin slices, saute onions and garlic, then blend into a silky creamy soup.","image":"https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?auto=format&fit=crop&w=800&q=80","sisterTip":"Хулууны үр эсвэл сухари дээр нь цацвал яг ресторанд идэж байгаа мэт болно.","sisterTipEn":"Top with toasted pumpkin seeds and croutons.","timerMinutes":null,"heatLevel":null,"stepIngredients":null,"toolsNeeded":null}]'::jsonb
  ),
  (
    'italian-tomato-soup',
    'Томат ба Базиликтай Итали Зутан Шөл',
    'Italian Tomato Basil Soup',
    'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
    ARRAY['Томат', 'Шөл', 'Итали'],
    '25 мин',
    'Easy',
    'Шөл ба Бүлээн хоол',
    'Italian',
    '{"calories":190,"protein":4,"carbs":24,"fat":9}'::jsonb,
    ARRAY['Улаан лооль', 'Базилик', 'Сармис', 'Оливын тос', 'Бальзамик цуу'],
    '[{"stepNumber":1,"title":"Томат буцалгах","titleEn":"Simmer & Puree","description":"Шинэхэн улаан лоолио сармис, базиликтай хамт 15 минут буцалгаад блендерээр зөөлөн зутан болгоно.","descriptionEn":"Simmer ripe tomatoes with fresh basil and garlic, then puree until velvety smooth.","image":"https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80","sisterTip":"Халуун талх дүрж идвэл маш сайхан амттай!","sisterTipEn":"Pair with warm toasted garlic bread.","timerMinutes":null,"heatLevel":null,"stepIngredients":null,"toolsNeeded":null}]'::jsonb
  ),
  (
    'broccoli-cheddar-soup',
    'Брокколи ба Чеддар Бяслагтай Эрүүл Шөл',
    'Healthy Broccoli Cheddar Soup',
    'https://images.unsplash.com/photo-1603105037880-880cd4edfb0d?auto=format&fit=crop&w=800&q=80',
    ARRAY['Брокколи', 'Бяслаг', 'Шөл'],
    '25 мин',
    'Medium',
    'Шөл ба Бүлээн хоол',
    'American',
    '{"calories":260,"protein":14,"carbs":18,"fat":16}'::jsonb,
    ARRAY['Брокколи', 'Чеддар бяслаг', 'Сүү', 'Сонгино', 'Гурил'],
    '[{"stepNumber":1,"title":"Брокколи чанаж бяслаг холих","titleEn":"Simmer & Melt Cheese","description":"Брокколигоо ногооны шөлөнд чанаад чеддар бяслаг ба сүү нэмэн өтгөрүүлж бэлтгэнэ.","descriptionEn":"Simmer fresh broccoli in vegetable stock, melt cheddar cheese into a warm savory soup.","image":"https://images.unsplash.com/photo-1603105037880-880cd4edfb0d?auto=format&fit=crop&w=800&q=80","sisterTip":"Брокколины хэсгээс жаахныг бүтнээр нь үлдээвэл зажлахад илүү амттай.","sisterTipEn":"Leave a few small broccoli florets whole for texture.","timerMinutes":null,"heatLevel":null,"stepIngredients":null,"toolsNeeded":null}]'::jsonb
  ),
  (
    'miso-tofu-soup',
    'Мисо Шөл ба Тофу, Вакаме Замаг',
    'Authentic Miso Tofu Soup',
    'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80',
    ARRAY['Мисо', 'Тофу', 'Япон'],
    '10 мин',
    'Easy',
    'Шөл ба Бүлээн хоол',
    'Japanese',
    '{"calories":140,"protein":10,"carbs":12,"fat":5}'::jsonb,
    ARRAY['Мисо паста', 'Тофу', 'Вакаме замаг', 'Ногоон сонгино', 'Даши шөл'],
    '[{"stepNumber":1,"title":"Мисо уусгах","titleEn":"Dissolve Miso & Serve","description":"Халуун усанд мисо пастагаа уусгаж тофу ба вакаме замгаа хийж 2 минут зөөлөн галаар халаана.","descriptionEn":"Whisk miso paste into warm dashi broth, add cubed silken tofu and seaweed.","image":"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80","sisterTip":"Мисогоо хэт буцалгаж болохгүй, шим тэжээл нь алдагдах аюултай.","sisterTipEn":"Do not boil miso paste directly; keep it simmering gently.","timerMinutes":null,"heatLevel":null,"stepIngredients":null,"toolsNeeded":null}]'::jsonb
  ),
  (
    'avocado-chocolate-mousse',
    'Авокадо ба Какаотой Шоколадан Мусс',
    'Avocado Dark Chocolate Mousse',
    'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=800&q=80',
    ARRAY['Шоколад', 'Дессерт', 'Авокадо'],
    '10 мин',
    'Easy',
    'Эрүүл дессерт ба Ундаа',
    'Healthy Sweet',
    '{"calories":230,"protein":4,"carbs":22,"fat":15}'::jsonb,
    ARRAY['Авокадо', 'Какао нунтаг', 'Агч модны сироп / Зөгийн бал', 'Ваниль', 'Бөөрөлзгөнө'],
    '[{"stepNumber":1,"title":"Блендерт өтгөрүүлэх","titleEn":"Blend Creamy Mousse","description":"Зөөлөрсөн авокадо, какао нунтаг, сиропыг блендерт хийж хилэн шиг торгомсог болтол нухна.","descriptionEn":"Blend ripe avocado, dark cocoa powder, and natural sweetener until velvety smooth.","image":"https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=800&q=80","sisterTip":"Хөргөгчид 30 минут хүйтэн байлгавал яг жинхэнэ мусс шиг өтгөрнө.","sisterTipEn":"Chill for 30 minutes before serving.","timerMinutes":null,"heatLevel":null,"stepIngredients":null,"toolsNeeded":null}]'::jsonb
  ),
  (
    'matcha-oat-latte',
    'Матча (Matcha) Лате ба Овъёосны Сүү',
    'Iced Matcha Latte with Oat Milk',
    'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=800&q=80',
    ARRAY['Матча', 'Ундаа', 'Овъёосны сүү'],
    '5 мин',
    'Easy',
    'Эрүүл дессерт ба Ундаа',
    'Japanese Drink',
    '{"calories":110,"protein":3,"carbs":14,"fat":4}'::jsonb,
    ARRAY['Япон матча нунтаг', 'Халуун ус', 'Овъёосны сүү', 'Мөс', 'Стевиа / Зөгийн бал'],
    '[{"stepNumber":1,"title":"Матча хутгах ба сүү юүлэх","titleEn":"Whisk Matcha & Pour Milk","description":"Матча нунтгаа халуун усанд хөөстэй болтол хутгаж уусгаад, мөстэй овъёосны сүүн дээрээ асгана.","descriptionEn":"Whisk matcha powder with hot water until foamy, pour over iced oat milk.","image":"https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=800&q=80","sisterTip":"Матча нь кофеноос илүү зөөлөн, удаан хугацааны эрч хүч өгдөг шүү!","sisterTipEn":"Matcha provides sustained calm energy without jitters.","timerMinutes":null,"heatLevel":null,"stepIngredients":null,"toolsNeeded":null}]'::jsonb
  ),
  (
    'ginger-lemon-detox-tea',
    'Цагаан Гаа ба Нимбэгтэй Детокс Цай',
    'Warm Ginger Lemon Detox Tea',
    'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80',
    ARRAY['Детокс', 'Цай', 'Цагаан гаа'],
    '5 мин',
    'Easy',
    'Эрүүл дессерт ба Ундаа',
    'Detox Drink',
    '{"calories":45,"protein":1,"carbs":10,"fat":0}'::jsonb,
    ARRAY['Шинэ цагаан гаа', 'Куркума нунтаг', 'Нимбэгийн шүүс', 'Зөгийн бал', 'Халуун ус'],
    '[{"stepNumber":1,"title":"Цай хандлах","titleEn":"Brew & Infuse","description":"Цагаан гаа ба куркумаг халуун усанд 5 минут хандлаж, нимбэг ба зөгийн балаар амтална.","descriptionEn":"Steep freshly grated ginger and turmeric in hot water for 5 mins. Add lemon and honey.","image":"https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80","sisterTip":"Өглөө өлөн элгэн дээрээ уувал дархлааг дэмжиж, хоол боловсруулахад тустай.","sisterTipEn":"Drink first thing in the morning to boost immunity.","timerMinutes":null,"heatLevel":null,"stepIngredients":null,"toolsNeeded":null}]'::jsonb
  ),
  (
    'berry-greek-energy-bowl',
    'Грек Тарагтай Бөөрөлзгөний Энержи Боул',
    'Greek Yogurt Raspberry Energy Bowl',
    'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=80',
    ARRAY['Тараг', 'Бөөрөлзгөнө', 'Дессерт'],
    '5 мин',
    'Easy',
    'Эрүүл дессерт ба Ундаа',
    'Healthy Snack',
    '{"calories":220,"protein":15,"carbs":24,"fat":6}'::jsonb,
    ARRAY['Грек тараг', 'Бөөрөлзгөнө', 'Гранола', 'Самрын үр', 'Зөгийн бал'],
    '[{"stepNumber":1,"title":"Боул таваглах","titleEn":"Assemble Energy Bowl","description":"Грек таргаа аяганд хийж, бөөрөлзгөнө, шаржигнасан гранола ба зөгийн балаар чимэглэнэ.","descriptionEn":"Spoon thick Greek yogurt into a bowl. Top with fresh berries, granola, and honey drizzle.","image":"https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=80","sisterTip":"Дессерт идэх хүслээ дарах хамгийн эрүүл бөгөөд уураглаг сонголт!","sisterTipEn":"The healthiest way to satisfy a dessert craving!","timerMinutes":null,"heatLevel":null,"stepIngredients":null,"toolsNeeded":null}]'::jsonb
  )
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  title_en = EXCLUDED.title_en,
  image = EXCLUDED.image,
  tags = EXCLUDED.tags,
  time = EXCLUDED.time,
  difficulty = EXCLUDED.difficulty,
  category = EXCLUDED.category,
  cuisine = EXCLUDED.cuisine,
  nutrition = EXCLUDED.nutrition,
  ingredients = EXCLUDED.ingredients,
  steps = EXCLUDED.steps;
